export const ERROR_CODES: { [key: string]: string } = {
  '00': 'Mesaj gönderildi',
  '01': 'Mesaj gönderildi fakat karakter sorunu var',
  '02': 'Kullanıcı adı veya şifre hatalı',
  '03': 'Mesaj başlığı sistemde tanımlı değil',
  '04': 'Parametreler eksik veya hatalı',
  '05': 'Gönderilecek telefon numarası yok',
  '06': 'Gönderilecek mesaj yok',
  '07': 'Tarih formatı hatalı',
  '08': 'Mesaj gönderim tarihinde hata var',
  '09': 'Tekrar eden mesaj',
  '10': 'Hatalı sorgulama',
  '11': 'Üyelik başlamamış veya sona ermiş',
  '12': 'Gönderim zamanı geçmiş',
  '13': 'Api desteklemiyor',
  '14': 'Aynı mesaj paketi tekrar gönderilmiş',
  '15': 'Mükerrer gönderim sınırı aşılmış',
  '16': 'Sistemsel hata',
  '17': 'Mesaj standart maksimum karakter sayısını aşıyor',
  '18': 'Geçersiz IP Adresi',
  '19': 'Gönderici adı sistemde tanımlı değil',
  '20': 'Şehir kodu hatalı',
  '21': 'Geçersiz dil parametresi',
  '22': 'Gönderim tipi desteklenmiyor',
  '23': 'Rezervasyon zamanı geçmiş mesaj',
  '24': 'Mükerrer gönderim sınırı aşılmış',
  '25': 'Kampanya ID hatalı',
  '30': 'Hesap aktivasyonu sağlanmamış',
  '31': 'Geçersiz sms tipi',
  '32': 'Hesap IP güvenlik kontrolünü desteklemiyor',
  '33': 'API IP güvenlik kontrolünü desteklemiyor',
  '34': 'Hesap API erişimine kapalı',
  '35': 'Hesap toplu sms gönderim iznine sahip değil',
  '36': 'Proje tanımlı değil',
  '37': 'Proje aktif değil',
  '38': 'Proje silinmiş',
  '40': 'Mesaj gönderimi için yeterli bakiye yok',
  '41': 'Mesaj paketi kullanım süresi aşılmış',
  '42': 'Mesaj gönderim simülasyonu başarılı',
  '43': 'Kullanıcı adı sistemde tanımlı değil',
  '44': 'Hatalı servis kullanımı',
  '45': 'Kullanıcı pasif',
  '46': 'Kullanıcı silinmiş',
  '47': 'Mesaj başlığı kullanıcıya tanımlı değil',
  '48': 'SMS alımı engellenmiş numara',
  '49': 'Gönderilen numaralardan hatalı olanlar var',
  '50': 'Abonelik iptal edilmiş',
  '51': 'SMS gönderimine kapalı hesap',
  '52': 'Geçersiz dağıtım listesi',
  '53': 'Gönderim zamanı kontrolü başarısız',
  '54': 'Mesaj paketi yetersiz',
  '55': 'Mükerrer gönderim',
  '56': 'Geçersiz görev tekrarı',
  '57': 'Geçersiz görev tekrar sonu',
  '58': 'Geçersiz görev tekrar aralığı',
  '59': 'Geçersiz çalışma zamanı',
  '60': 'Hesap API desteklemiyor',
  '61': 'Geçersiz IP tanımı',
  '62': 'Mesaj gönderim noktası aktif değil'
};